### PR TITLE
Support third party user installed boards

### PR DESCRIPTION
**Pull request by skalnik**
I added the [Sparkfun 32u4 boards](https://github.com/sparkfun/SF32u4_boards) to my arduino setup, but ino didn't find them. I don't really know python, but I gave it a stab in trying to get it to glob and find any board.txt files in subfolders of the hardware dir. Works on my machine. Any and all feedback welcome.

Probably could use some tests, but I wanted to open the PR up ASAP. Will investigate adding some :smile_cat:

### CODE REVIEW

**Comment by kabturek** [comment]
:+1: for this one

**Comment by itayd** [comment]
+1

**Comment by skalnik** [comment]
@nailxx It seems like you've been merging PRs for this recently. Any chance of this getting merged along with some other outstanding PRs? Or does anyone know of a better maintained fork?

**Comment by bwagner** [comment]
:+1:

**Comment by itayd** [comment]
+1

**Comment by KGardevoir** [comment]
This is actually broken for systems with multiple avr-gcc, make, etc (for instance if you have arduino installed BUT also have the avr-gcc installed)

**Comment by skalnik** [comment]
@KGardevoir Suggestions on a fix?

**Comment by KGardevoir** [comment]
See PR#159

**Comment by skalnik** [comment]
Nice! Closing in favor of https://github.com/amperka/ino/pull/159

**Pull request closed without merging**
